### PR TITLE
zh-CN localization

### PR DESCRIPTION
**Pull request by fang5566**
make a zh-CN localization for Chinese users.

### CODE REVIEW

**Comment by fang5566** [comment]
Please add this zh-CN locales to the main project.

**Comment by cadeyrn** [comment]
Thank you very much! :)

**Comment by cadeyrn** [comment]
Enterprise Policy Generator 3.1 with your translation has been released.

**Comment by fang5566** [comment]
Thanks for your speed work

    
        
            
                
                    
                        
                    
                    
                        
                            Carlos Oliveira
                            
                            
                                
                                    邮箱：wlq105556@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
On 08/05/2018 15:29, Sören Hentzschel wrote: Enterprise Policy Generator 3.1 with your translation has been released.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cadeyrn/enterprise-policy-generator","title":"cadeyrn/enterprise-policy-generator","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cadeyrn/enterprise-policy-generator"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cadeyrn in #31: Enterprise Policy Generator 3.1 with your translation has been released."}],"action":{"name":"View Pull Request","url":"https://github.com/cadeyrn/enterprise-policy-generator/pull/31#issuecomment-410501641"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cadeyrn/enterprise-policy-generator/pull/31#issuecomment-410501641",
"url": "https://github.com/cadeyrn/enterprise-policy-generator/pull/31#issuecomment-410501641",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [cadeyrn/enterprise-policy-generator] zh-CN localization (#31)",
"sections": [
{
"text": "",
"activityTitle": "**Sören Hentzschel**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@cadeyrn",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"cadeyrn/enterprise-policy-generator\",\n\"issueId\": 31,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/cadeyrn/enterprise-policy-generator/pull/31#issuecomment-410501641"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 360622570\n}"
}
],
"themeColor": "26292E"
}
]

**Pull request merged**
