### PR TITLE
Create French translation

### PR DESCRIPTION
**Pull request by xerta555**
Hello,

There is the French translation for this addon.
If u quote names of translators, just name me Rom please.

### CODE REVIEW

**Comment by cadeyrn** [comment]
Thank you very much!

I am working on the next version 2.0.0 of the Enterprise Policy Generator and a few new translations will be needed. What is the best way to inform you about the new needed translations once I know what has to be translated?

**Comment by xerta555** [comment]
> I am working on the next version 2.0.0 of the Enterprise Policy Generator and a few new translations will be needed. What is the best way to inform you about the new needed translations once I know what has to be translated?

Hello, to inform me about new avalaible strings version, i suggest you to open an issue on your repo and quote me with the "@" symbol, normaly i will receive a email about that.

**Comment by cadeyrn** [comment]
@xerta555 Hi!

Finally I was able to complete the work for the big new feature of Enterprise Policy Generator 2.0.0, the ability to save and load configurations. I don't know why there are some of my commits in your pull request, maybe it's the easiest to close this and create a new pull request.

May I ask you to update your translation to incorporate the new strings? You can see the changes here:

https://github.com/cadeyrn/enterprise-policy-generator/commit/e3c42239303533a82175b63bfc94c5cd786e6956#diff-8f8a17eeb3eb8b6cc636fb8f10d5ae13

(you will see that there are some duplicated strings so it's not that much to translate. I probably will simplify this a bit but I can take care of the French translation once your translations are merged).

Another note: double quoted strings have to be escaped, for example:

… créer un répertoire appelé "distribution" da …

should be:

… créer un répertoire appelé \"distribution\" da …

on the other hand, single quoted strings don't have to be escaped. For example:

… jusqu\'à ce qu\'ils expirent …

should be:

… jusqu'à ce qu'ils expirent …

Both changes are necessary, otherwise the translation will not work.

Thank you!

**Comment by cadeyrn** [comment]
And these are two other new strings:
https://github.com/cadeyrn/enterprise-policy-generator/commit/829ad23fcec2926da2dce7c354c1fd7369d29808#diff-8f8a17eeb3eb8b6cc636fb8f10d5ae13

**Comment by cadeyrn** [comment]
And:

https://github.com/cadeyrn/enterprise-policy-generator/commit/f5186e205aa90786c2b765ca1d2873841c937206#diff-869200a8548d888da8a18799c8ee9ac3

https://github.com/cadeyrn/enterprise-policy-generator/commit/ec70823aa40421b354b494d3e9a8c8c59a92b2d0#diff-8f8a17eeb3eb8b6cc636fb8f10d5ae13

Now version 2.0 is complete. There won't be more strings to translate for this version.

Thank you.

**Comment by xerta555** [comment]
Ok, so now there is again one last `:` highlighted in red at the line 305.

If another small ajustments, typo must to be make, say to me.

**Comment by cadeyrn** [comment]
It was highlighted because of a missing comma in the line before. I merged your pull request and fixed it already.

Thank you very much for the translation! :)

**Pull request merged**
